import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Link from 'next/link'
import 'src/components/Navbar/Navbar.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </head>
      <body>
      <div className='hidden md:block z-40 w-full text-center pt-4'>
        <div className='inline-flex gap-100'>
          <Link className="text-sm text-stone-900 font-medium mx-4" href={'/'}>HOME</Link>
          <Link className="text-sm text-stone-900 font-medium mx-4" href={'/about'}>ABOUT</Link>
          <Link className="text-sm text-stone-900 font-medium mx-4" href={'/projects'}>PROJECTS</Link>
        </div>
      </div>

      <div className="flex flex-col h-full absolute top-36 right-20 mt-64">
        <Navbar mode='dark'/>
      </div>
        {children}
        </body>
    </html>
  )
}
